### ISSUE TITLE
Loop through elements in AutoLinearLayoutView

### ISSUE THREAD

**Issue by jaytj95** [qianbin/AutoLinearLayoutView#2]
Is this possible?

**Comment by qianbin** [comment]
What does that exactly mean?

**Comment by jaytj95** [comment]
I was looking to be able to get the elements of the LinearLayout as an array and iterate through them.

I found my solution in `linearLayout.subviews` and `linearLayout.subviews.count` which gave me an array of the views inside my layout and the number of views, respectively. 

Thanks!
